#!/usr/bin/env bash
set -euo pipefail

PACKAGE_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PACKAGE="$PACKAGE_ROOT/Package.swift"
QUANTIZER="$PACKAGE_ROOT/Sources/ModelQuantizer/main.swift"
RESCORER="$PACKAGE_ROOT/Sources/LagunaScaleSearchRescorer/LagunaScaleSearchRescorer.swift"
RESCORER_CLI="$PACKAGE_ROOT/Sources/LagunaScaleSearchRescorerCLI/main.swift"
LAGUNA_MODEL="$PACKAGE_ROOT/Sources/ModelRunnerCore/LagunaModel.swift"
DFLASH_MODEL="$PACKAGE_ROOT/Sources/ModelRunnerCore/LagunaDFlashModel.swift"
MIXTRAL_TEST="$PACKAGE_ROOT/Tests/ModelQuantizerTests/MixtralScaleSearchConversionTests.swift"
DFLASH_TEST="$PACKAGE_ROOT/Tests/ModelQuantizerTests/DFlashScaleSearchConversionTests.swift"
MIXTRAL_FIXTURE="$PACKAGE_ROOT/Tests/Fixtures/MixtralTiny/config.json"
MISTRAL_FIXTURE="$PACKAGE_ROOT/Tests/Fixtures/MistralTiny/config.json"
GPT_OSS_FIXTURE="$PACKAGE_ROOT/Tests/Fixtures/GPTOSSTiny/config.json"
DFLASH_FIXTURE="$PACKAGE_ROOT/Tests/Fixtures/LagunaDFlashTiny/config.json"

grep -Fq 'name: "model-runner-quantize"' "$PACKAGE"
grep -Fq 'name: "ModelQuantizerTests"' "$PACKAGE"
grep -Fq 'midnight|model-runner-quantize|' "$PACKAGE_ROOT/build.sh"
grep -Fq 'LLMTypeRegistry.shared.createModel' "$QUANTIZER"
grep -Fq 'LLMModelFactory.shared.convert' "$QUANTIZER"
grep -Fq 'name: .customLong("standard-q4")' "$QUANTIZER"
grep -Fq 'calibration: standardQ4 ? .standard : .q4AffineScaleSearch' "$QUANTIZER"
grep -Fq 'mlx_affine_q4_standard' "$QUANTIZER"
grep -Fq 'standard-q4-quantization.json' "$QUANTIZER"
grep -Fq 'scale-search-quantization.json' "$QUANTIZER"
grep -Fq 'plan.scaleSearchPaths.union(plan.standardQ4Paths).sorted()' "$QUANTIZER"
grep -Fq -- '--standard-q4 is a generic-conversion control' "$QUANTIZER"
grep -Fq 'module is Linear || module is SwitchLinear' "$QUANTIZER"
grep -Fq '.block_sparse_moe.gate' "$QUANTIZER"
grep -Fq '.mlp.router' "$QUANTIZER"
grep -Fq '.mlp.gate.proj' "$QUANTIZER"
grep -Fq 'DFlashLagunaForCausalLM' "$QUANTIZER"
grep -Fq 'MTPDrafterTypeRegistry.shared.createModel' "$QUANTIZER"
grep -Fq 'MLXLMCommon.convert' "$QUANTIZER"
grep -Fq 'mandatoryQ8Suffixes: ["fc", ".self_attn.g_proj"]' "$QUANTIZER"
grep -Fq 'mandatory Q8 module(s) cannot be skipped' "$QUANTIZER"
grep -Fq 'LagunaScaleSearchRescorer.rescore' "$QUANTIZER"
grep -Fq 'public struct LagunaScaleSearchRescorer' "$RESCORER"
grep -Fq 'LagunaScaleSearchRescorer.main()' "$RESCORER_CLI"
grep -Fq 'public enum LagunaModelRegistration' "$LAGUNA_MODEL"
grep -Fq 'public enum LagunaDFlashRegistration' "$DFLASH_MODEL"
grep -Fq 'block_sparse_moe.switch_mlp.gate_proj.scales' "$MIXTRAL_TEST"
grep -Fq 'routerQuantization.bits, 8' "$MIXTRAL_TEST"
grep -Fq 'calibration: .standard' "$MIXTRAL_TEST"
grep -Fq 'XCTAssertEqual(Set(outputArrays.keys), Set(standardArrays.keys))' "$MIXTRAL_TEST"
grep -Fq 'testDFlashFusedCheckpointConvertsAndReloads' "$DFLASH_TEST"
grep -Fq 'MTPDrafterTypeRegistry.shared.createModel' "$DFLASH_TEST"
grep -Fq 'gate_up_proj.scales' "$DFLASH_TEST"
grep -Fq '"model_type": "mixtral"' "$MIXTRAL_FIXTURE"
grep -Fq '"model_type": "mistral"' "$MISTRAL_FIXTURE"
grep -Fq '"model_type": "gpt_oss"' "$GPT_OSS_FIXTURE"
grep -Fq '"DFlashLagunaForCausalLM"' "$DFLASH_FIXTURE"
test ! -e "$PACKAGE_ROOT/Sources/LagunaScaleSearchRescorer/main.swift"

echo "Generic Swift ScaleSearch quantizer checks passed"
